name: Python CI/CD

on:
  push:
    branches: [ main ]

permissions:
  contents: write   # ✅ required for deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: "Python Demo Release ${{ github.run_number }}"
          body: "Auto release from CI/CD pipeline"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
